db:
  type: postgresql:10
  disk: 2048
  configuration:
    databases:
      - gobelins
    endpoints:
      gobelins:
        privileges:
          gobelins: admin

es:
  type: elasticsearch:7.10
  disk: 256
  configuration:
    plugins:
      - analysis-icu

cache:
  type: redis:7.0

rabbitmq:
  type: rabbitmq:3.12
  disk: 256